# Generated by Django 5.0 on 2023-12-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("pdf", models.FileField(upload_to="pdfs/")),
            ],
        ),
        migrations.CreateModel(
            name="Section_one",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_ar", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_ar", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.FileField(blank=True, null=True, upload_to="careers/"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section_two",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_ar", models.CharField(max_length=50)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_ar", models.TextField(blank=True, null=True)),
                ("reports", models.ManyToManyField(to="suppliers.reports")),
            ],
        ),
    ]
