# Generated by Django 5.0 on 2023-12-20 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reports",
            name="title_ar",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
