# Generated by Django 5.0 on 2023-12-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("suppliers", "0002_reports_title_ar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="section_two",
            name="reports",
            field=models.ManyToManyField(blank=True, null=True, to="suppliers.reports"),
        ),
    ]
