# Generated by Django 5.0 on 2023-12-20 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Envronmental_section_one",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="images/")),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Envronmental_section_two",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_ar", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="files",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pdf", models.FileField(upload_to="pdf/")),
            ],
        ),
        migrations.CreateModel(
            name="Social_section_one",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="images/")),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Social_section_two",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_ar", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Tab",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_ar", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Governance_section_one",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.FileField(upload_to="images/")),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
                ("pdf", models.ManyToManyField(to="sustainability.files")),
            ],
        ),
        migrations.CreateModel(
            name="Social",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainability.social_section_one",
                    ),
                ),
                (
                    "section_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainability.social_section_two",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Tabs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_ar", models.CharField(max_length=50)),
                ("tab", models.ManyToManyField(to="sustainability.tab")),
            ],
        ),
        migrations.CreateModel(
            name="Envronmental",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainability.envronmental_section_one",
                    ),
                ),
                (
                    "section_two",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainability.envronmental_section_two",
                    ),
                ),
                (
                    "tabs",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="sustainability.tabs",
                    ),
                ),
            ],
        ),
    ]
