# Generated by Django 5.0 on 2023-12-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sustainability", "0003_governance_section_one_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="files",
            name="title",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="files",
            name="title_ar",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
