# Generated by Django 5.0 on 2023-12-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sustainability", "0004_files_title_files_title_ar"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crs_section_four",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_ar", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
                ("image", models.FileField(upload_to="images/")),
            ],
        ),
        migrations.CreateModel(
            name="Crs_section_one",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_ar", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="descriptions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="statistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_ar", models.CharField(max_length=50)),
                ("number", models.IntegerField()),
                ("symbol", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Crs_section_three",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_ar", models.CharField(max_length=50)),
                (
                    "description",
                    models.ManyToManyField(to="sustainability.descriptions"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Crs_section_two",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_ar", models.CharField(max_length=50)),
                ("statistics", models.ManyToManyField(to="sustainability.statistics")),
            ],
        ),
    ]
