# Generated by Django 5.0 on 2023-12-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sustainability", "0006_sustainability_reports"),
    ]

    operations = [
        migrations.CreateModel(
            name="Certifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("pdf", models.FileField(upload_to="pdfs/")),
            ],
        ),
        migrations.CreateModel(
            name="Ims_reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("year", models.CharField(max_length=100)),
                ("pdf", models.FileField(upload_to="pdfs/")),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.AlterModelOptions(
            name="sustainability_reports",
            options={"ordering": ["-year"]},
        ),
    ]
