# Generated by Django 5.0 on 2023-12-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sustainability", "0007_certifications_ims_reports_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crs_section_three",
            name="description",
            field=models.ManyToManyField(
                blank=True, null=True, to="sustainability.descriptions"
            ),
        ),
        migrations.AlterField(
            model_name="crs_section_two",
            name="statistics",
            field=models.ManyToManyField(
                blank=True, null=True, to="sustainability.statistics"
            ),
        ),
        migrations.AlterField(
            model_name="governance_section_one",
            name="pdf",
            field=models.ManyToManyField(
                blank=True, null=True, to="sustainability.files"
            ),
        ),
        migrations.AlterField(
            model_name="tabs",
            name="tab",
            field=models.ManyToManyField(
                blank=True, null=True, to="sustainability.tab"
            ),
        ),
    ]
