# Generated by Django 5.0 on 2024-01-09 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sustainability", "0009_alter_crs_section_four_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="envronmental",
            name="section_two",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sustainability.envronmental_section_two",
            ),
        ),
        migrations.AlterField(
            model_name="envronmental",
            name="tabs",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="sustainability.tabs",
            ),
        ),
    ]
