# Generated by Django 5.0 on 2023-12-20 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Section_one",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
                (
                    "image",
                    models.ImageField(upload_to="digital_transformation/section_one"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section_three",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
                (
                    "image",
                    models.ImageField(upload_to="digital_transformation/section_one"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section_two",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Digital_transformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
                (
                    "section_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="innovation.section_one",
                    ),
                ),
                (
                    "section_three",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="innovation.section_three",
                    ),
                ),
                ("section_two", models.ManyToManyField(to="innovation.section_two")),
            ],
        ),
    ]
