# Generated by Django 5.0 on 2023-12-20 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innovation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Section_four_research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                (
                    "icon",
                    models.FileField(upload_to="digital_transformation/section_one"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section_one_research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
                (
                    "image",
                    models.ImageField(upload_to="digital_transformation/section_one"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section_three_research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
                (
                    "image",
                    models.ImageField(upload_to="digital_transformation/section_one"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Section_two_research",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Research_and_development",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
                (
                    "section_one",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="innovation.section_one_research",
                    ),
                ),
                (
                    "section_foure",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="innovation.section_three_research",
                    ),
                ),
                (
                    "section_three",
                    models.ManyToManyField(to="innovation.section_two_research"),
                ),
            ],
        ),
    ]
