# Generated by Django 5.0 on 2023-12-20 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("innovation", "0002_section_four_research_section_one_research_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="research_and_development",
            name="section_two",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="innovation.section_four_research",
            ),
            preserve_default=False,
        ),
    ]
