# Generated by Django 5.0 on 2024-01-08 07:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0002_contact_address_ar_contact_description_ar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="aditional_info",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="aditional_info_ar",
            field=ckeditor.fields.RichTextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="locaction",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="contact",
            name="locaction_ar",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
