# Generated by Django 5.0 on 2024-01-08 07:26

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0003_contact_aditional_info_contact_aditional_info_ar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="aditional_info",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="aditional_info_ar",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="locaction",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="locaction_ar",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
