# Generated by Django 5.0 on 2024-01-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_alter_contact_aditional_info_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="website",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
