# Generated by Django 5.0 on 2024-01-08 07:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0005_contact_website"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="locaction_ar",
        ),
    ]
