# Generated by Django 5.0 on 2024-01-08 07:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0006_remove_contact_locaction_ar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="contact",
            name="aditional_info",
        ),
        migrations.RemoveField(
            model_name="contact",
            name="aditional_info_ar",
        ),
    ]
