# Generated by Django 5.0 on 2023-12-18 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_delete_products_banner_title_ar_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careers",
            name="image",
            field=models.FileField(null=True, upload_to="careers/"),
        ),
        migrations.AlterField(
            model_name="sipchem",
            name="icon",
            field=models.FileField(upload_to="sipchem/"),
        ),
        migrations.AlterField(
            model_name="sustainability",
            name="icon",
            field=models.FileField(null=True, upload_to="sustainability/"),
        ),
    ]
