# Generated by Django 5.0 on 2023-12-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0003_alter_careers_image_alter_sipchem_icon_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("title_ar", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
            ],
        ),
    ]
