# Generated by Django 5.0 on 2023-12-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0004_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="careers",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="careers",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="careers",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="careers/"),
        ),
        migrations.AlterField(
            model_name="sustainability",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sustainability",
            name="description_ar",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sustainability",
            name="icon",
            field=models.FileField(blank=True, null=True, upload_to="sustainability/"),
        ),
    ]
