# Generated by Django 5.0 on 2023-12-25 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0005_alter_careers_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="banner",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="banner",
            name="title_ar",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="careers",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="careers",
            name="title_ar",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="investors",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="investors",
            name="title_ar",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="products",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="products",
            name="title_ar",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="sipchem",
            name="subtitle",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="sipchem",
            name="subtitle_ar",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="sipchem",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="sipchem",
            name="title_ar",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="sustainability",
            name="title",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="sustainability",
            name="title_ar",
            field=models.CharField(max_length=500),
        ),
    ]
