# Generated by Django 5.0 on 2023-12-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="section_five",
            name="name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="section_five",
            name="name_ar",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
