# Generated by Django 5.0 on 2023-12-19 02:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product_specification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("pdf", models.FileField(upload_to="pdfs/")),
            ],
        ),
        migrations.CreateModel(
            name="Safety_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("pdf", models.FileField(upload_to="pdfs/")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("description_ar", models.TextField()),
                (
                    "images",
                    models.ManyToManyField(
                        related_name="product_images", to="products.product"
                    ),
                ),
                (
                    "product_specifications",
                    models.ManyToManyField(to="products.product_specification"),
                ),
                ("safety_data", models.ManyToManyField(to="products.safety_data")),
            ],
        ),
    ]
