# Generated by Django 5.0 on 2023-12-19 03:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="images",
            name="image",
            field=models.FileField(upload_to="images/"),
        ),
    ]
