# Generated by Django 5.0 on 2023-12-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_alter_images_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="sub_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("title_ar", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="category",
            name="sub_category",
            field=models.ManyToManyField(to="products.sub_category"),
        ),
    ]
