# Generated by Django 5.0 on 2023-12-23 23:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_sub_category_category_sub_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="sub_category",
        ),
        migrations.AddField(
            model_name="product",
            name="sub_category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.sub_category",
            ),
            preserve_default=False,
        ),
    ]
