# Generated by Django 5.0 on 2023-12-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0006_remove_category_sub_category_product_sub_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="product_images",
                to="products.images",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_specifications",
            field=models.ManyToManyField(
                blank=True, null=True, to="products.product_specification"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="safety_data",
            field=models.ManyToManyField(
                blank=True, null=True, to="products.safety_data"
            ),
        ),
    ]
